### ISSUE TITLE
asus 天选4 warning

### ISSUE THREAD

**Issue by ruomeng150** [DanKE123abc/HiPcMijia#3]
[Log.log](https://github.com/DanKE123abc/HiPcMijia/files/14001496/Log.log)
[Error.log](https://github.com/DanKE123abc/HiPcMijia/files/14001497/Error.log)
[Warning.log](https://github.com/DanKE123abc/HiPcMijia/files/14001498/Warning.log)

**Comment by DanKE123abc** [comment]
......
你是不是没改Config
![屏幕截图 2024-01-28 170740](https://github.com/DanKE123abc/HiPcMijia/assets/98072464/5d050038-6f97-4572-ab5d-4177932ebe9f)
